version: '3.8'

services:
  api-tests:
    build: .
    environment:
      BASE_URL: https://fakerestapi.azurewebsites.net
    volumes:
      - ./build/allure-results:/app/build/allure-results
      - ./build/reports:/app/build/reports
    command: ./gradlew --no-daemon test allureReport
    networks:
      - test-network

  report-server:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./build/reports/allure-report/allureReport:/usr/share/nginx/html
    depends_on:
      - api-tests
    networks:
      - test-network

networks:
  test-network:
    driver: bridge